# --- !Ups

CREATE TABLE "ROLE" (
  "ID"        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "NAME"      VARCHAR(50)                                             NOT NULL,
  "CREATEDAT" TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "USER" (
  "ID"        VARCHAR   NOT NULL PRIMARY KEY,
  "FIRSTNAME" VARCHAR(50),
  "LASTNAME"  VARCHAR(50),
  "FULLNAME"  VARCHAR(100),
  "EMAIL"     VARCHAR(50),
  "AVATARURL" VARCHAR,
  "ACTIVATED" BOOLEAN            DEFAULT FALSE,
  "ROLE_ID"   BIGINT             DEFAULT 0,
  "CREATEDAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT userUniqueEmail UNIQUE (EMAIL),
  CONSTRAINT fkUserRole FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

CREATE TABLE "LOGININFO" (
  "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "PROVIDERID"  VARCHAR                                                 NOT NULL,
  "PROVIDERKEY" VARCHAR                                                 NOT NULL
);

CREATE TABLE "USERLOGININFO" (
  "USER_ID"      VARCHAR NOT NULL,
  "LOGININFO_ID" BIGINT  NOT NULL
);

CREATE TABLE "PASSWORDINFO" (
  "HASHER"       VARCHAR NOT NULL,
  "PASSWORD"     VARCHAR NOT NULL,
  "SALT"         VARCHAR,
  "LOGININFO_ID" BIGINT  NOT NULL
);

CREATE TABLE "OAUTH1INFO" (
  "ID"           BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "TOKEN"        VARCHAR                                                 NOT NULL,
  "SECRET"       VARCHAR                                                 NOT NULL,
  "LOGININFO_ID" BIGINT                                                  NOT NULL
);

CREATE TABLE "OAUTH2INFO" (
  "ID"           BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "ACCESSTOKEN"  VARCHAR                                                 NOT NULL,
  "TOKENTYPE"    VARCHAR,
  "EXPIRESIN"    INTEGER,
  "REFRESHTOKEN" VARCHAR,
  "LOGININFO_ID" BIGINT                                                  NOT NULL
);

CREATE TABLE "OPENIDINFO" (
  "ID"           VARCHAR NOT NULL PRIMARY KEY,
  "LOGININFO_ID" BIGINT  NOT NULL
);

CREATE TABLE "OPENIDATTRIBUTES" (
  "ID"    VARCHAR NOT NULL,
  "KEY"   VARCHAR NOT NULL,
  "VALUE" VARCHAR NOT NULL
);

CREATE TABLE "PROFILE" (
  "ID"                     BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "YEARSOFEXPERIENCE"      SMALLINT                                                         DEFAULT 0,
  "NUMBEROFRECOMENDATIONS" SMALLINT                                                         DEFAULT 0,
  "NUMBEROFCASES"          SMALLINT                                                         DEFAULT 0,
  "ABOUTME"                VARCHAR                                                 NULL,
  "CREATEDAT"              TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "AVATARURL"              VARCHAR,
  "USER_ID"                VARCHAR,
  CONSTRAINT fkProfileUser FOREIGN KEY (USER_ID) REFERENCES USER (ID),
);


CREATE TABLE "SPECIALITY" (
  "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "NAME"        VARCHAR(50)                                             NOT NULL,
  "DESCRIPTION" VARCHAR(200)                                            NOT NULL,
  "CREATEDAT"   TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT specialityUniqueName UNIQUE (NAME)
);

CREATE TABLE "EXPERTS" (
  "ID"            BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "FULLNAME"      VARCHAR(100)                                            NOT NULL,
  "ISAPPROVED"    BOOLEAN                                                          DEFAULT FALSE,
  "USER_ID"       VARCHAR,
  "SPECIALITY_ID" BIGINT,
  "CREATEDAT"     TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fkExpertUser FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  CONSTRAINT fkExpertSpeciality FOREIGN KEY (SPECIALITY_ID) REFERENCES SPECIALITY (ID)
);

CREATE TABLE "AGENDA" (
  "ID"      BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "USER_ID" VARCHAR,
  CONSTRAINT fkAgendaUser FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE "AGENDAENTRY" (
  "ID"        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "ISFREE"    BOOLEAN DEFAULT TRUE,
  "STARTDATE" TIMESTAMP                                               NOT NULL,
  "USER_ID"   VARCHAR,
  CONSTRAINT fkAgendaEntry FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);


CREATE TABLE "PARTNER" (
  "ID"                BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "FIRSTNAME"         VARCHAR(70)                                             NOT NULL,
  "LASTNAME"          VARCHAR(70)                                             NOT NULL,
  "EMAIL"             VARCHAR(70)                                             NOT NULL,
  "YEARSOFEXPERIENCE" SMALLINT                                                NOT NULL                   DEFAULT 0,
  "NUMBEROFCASES"     SMALLINT                                                NOT NULL                   DEFAULT 0,
  "WASAPPROVED"       BOOLEAN                                                                            DEFAULT FALSE,
  "CREATEDAT"         TIMESTAMP                                               NOT NULL                   DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "SESSION" (
  "ID"                BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "PROFESSIONALNOTES" VARCHAR,
  "AGENDAENTRY_ID"    BIGINT,
  "SPECIALITY_ID"     BIGINT,
  "PROFESSIONAL_ID"   VARCHAR,
  "CUSTOMER_ID"       VARCHAR,
  "ROOM_ID"           VARCHAR,
  "SESSION_STATE"     SMALLINT                                                         DEFAULT 0,
  "CREATEDAT"         TIMESTAMP                                               NOT NULL DEFAULT CURRENT_TIMESTAMP
);


# --- !Downs

DROP TABLE "ROLE";
DROP TABLE "USER";
DROP TABLE "LOGININFO";
DROP TABLE "USERLOGININFO";
DROP TABLE "PASSWORDINFO";
DROP TABLE "OAUTH1INFO";
DROP TABLE "OAUTH2INFO";
DROP TABLE "OPENIDINFO";
DROP TABLE "OPENIDATTRIBUTES";
DROP TABLE "PROFILE";
DROP TABLE "SPECIALITY";
DROP TABLE "EXPERTS";
DROP TABLE "AGENDA";
DROP TABLE "AGENDAENTRY";
DROP TABLE "PARTNER"